### ISSUE TITLE
[Bug]: the app crashes when the video source is disconnected

### ISSUE THREAD

**Issue by ljgdasfhk** [TokTok/qTox#281]
### Contact Details (e.g. Tox ID or email)

230A564AA9C455AB79CFE496E48735BD4429E93D43223666F13C555F8524C929503DBB841ECB

### qTox Version

nightly

### Steps to reproduce

1. Start qTox (portable)
2. start a video call
3. switch video source to desktop
4. switch video source to "missing"

### Observed Behavior

the application stops responding and crashes

### Expected Behavior

video transmission must stop

### Reproducibility

Always

### Operating System

Windows

### Operating System version/distro/name/etc.

Windows 11

**Comment by iphydf** [comment]
#278 might fix this. Can you see if the binary from https://github.com/TokTok/qTox/actions/runs/12446816994/job/34749627648#step:7:23 has the same issue?

**Comment by ljgdasfhk** [comment]
I'll check it next week

**Comment by iphydf** [comment]
I can reproduce a deadlock when following your instructions. #278 does not fix that one. I can't reproduce a crash, but I'll have a look at that deadlock as well.

**Comment by iphydf** [comment]
The crash is caused by toxav reading a free'd buffer.

The `free` happens here:
```
0x00031f221500 is located 2592000 bytes inside of 3110401-byte region [0x00031efa8800,0x00031f29fe01)
freed by thread T6 here:
    #0 0x10b0b8d40 in free+0x98 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x54d40)
    #1 0x1035a7110 in VideoFrame::deleteFrameBuffer() videoframe.cpp:666
    #2 0x1035ab4c0 in VideoFrame::releaseFrame() videoframe.cpp:261
    #3 0x1035aa608 in VideoFrame::untrackFrames(unsigned long long const&, bool) videoframe.cpp:243
    #4 0x10355e3b8 in CameraSource::closeDevice() camerasource.cpp:361
    #5 0x10355d258 in CameraSource::setupDevice(QString const&, VideoMode const&) camerasource.cpp:150
```

Then it's read here:
```
    #0 0x10b0b6da4 in memcpy+0x3fc (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x52da4)
    #1 0x1060c159c in toxav_video_send_frame+0x254 (qtox:arm64+0x10409d59c)
    #2 0x102c9edbc in CoreAV::sendCallVideo(unsigned int, std::__1::shared_ptr<VideoFrame>) coreav.cpp:411
    #3 0x102d97fac in ToxFriendCall::ToxFriendCall(unsigned int, bool, CoreAV&, IAudioControl&, CameraSource&)::$_1::operator()(std::__1::shared_ptr<VideoFrame>) const toxcall.cpp:136
```

The problem is that the video frames that are in flight from the video device to the video send function are cleared while in flight when the video device is closed. The fix is feasible but non-trivial, so I'm moving this to the next milestone. In the meantime, if you want to switch video device, you should close the call first.

**Comment by ljgdasfhk** [comment]
I noticed that version 1.17.6 does not crash under the same conditions

**Comment by ljgdasfhk** [comment]
by the way, preventing the user from changing the video source is a limitation of functionality, it will make it impossible to switch between the front and rear cameras, and in general...

**Comment by iphydf** [comment]
Yes, I agree this is a limitation, and we will fix the bug, but we can't fix it before the upcoming release.

1.17.6 doesn't crash because it happens to accidentally not crash. The same issue exists there, but out of sheer luck, it doesn't happen. It might be because Qt5 has a different order of execution in callbacks/slots. Does the issue happen in [1.18.0-rc.1](https://github.com/TokTok/qTox/releases/tag/v1.17.90)? If yes, then no changes have happened since 1.17.6 in qtox that could possibly affect the behaviour there.

**Comment by iphydf** [comment]
Can you test this on the 1.18.0 release?

**Comment by iphydf** [comment]
I've tested this a few times on Windows and macOS, and I can no longer crash the app. Please reopen this if you can still reproduce.

**Comment by ljgdasfhk** [comment]
At first glance, this problem is solved. But there are still questions about the video sources.
If I have two monitors, then when selecting the second monitor, we do not receive its image.
If during a video call we press the "full screen" button, then firstly, we do not have the opportunity to return back to the conversation window, secondly, the image does not expand to the full screen, but its size matches its size inside the conversation window, and thirdly, if we press "conversation in a separate window", the video call image disappears forever.
Should I create a separate note for these questions?

**Comment by iphydf** [comment]
Yes please open a new issue for those things.
